nama = input('Masukan nama :')
kelas = input('Masukan kelas :')
# print('\n')
print('Nama saya '+ nama + ', Kelas Saya ' + kelas)
# print('Nama saya : ', nama, ' Kelas Saya : ', kelas)
# print('Nama saya', nama)
# print('Kelas saya :', kelas)